<template>
<div class="competition">
  <h2>300 талантов для "Королевы"</h2>
  <label>
    Выберите пол:
    <select v-model="gender">
      <option value="male">Мужской</option>
      <option value="female">Женский</option>
    </select>
  </label>

  <div
    v-for="(event, index) in events"
    :key="event.name"
    class="event-form"
    style="margin-top: 20px;"
  >
    <label :for="'event-' + index">{{ event.name }}:</label>

    <template v-if="event.name === 'Бег 500/800м' || event.name === 'Бег 800/1000м'">
      <!-- Ввод времени для 500/800м и 800/1000м -->
      <input
        :id="'event-' + index"
        type="text"
        v-model="event.resultInput"
        @input="onTimeInput(index)"
        placeholder="MM:SS,ms (например, 01:55,3)"
      />
    </template>

    <template v-else>
      <!-- Числовой ввод для всех остальных -->
      <input
        :id="'event-' + index"
        type="number"
        v-model.number="event.result"
        @input="calculatePoints(index)"
        placeholder="Введите результат"
        min="0"
        step="any"
      />
    </template>

    <span style="margin-left: 10px;">Очки: {{ event.points }}</span>
  </div>

  <h2>Итоговая сумма очков: {{ totalPoints }}</h2>
</div>
</template>

<script>
export default {
data() {
  return {
    gender: "male",
    events: [
      {
        name: "Бег 30м",
        resultsArray: [],
        result: 0,
        points: 0,
        isTimeBased: true,
        resultInput: "",
      },
      {
        name: "Прыжки в длину",
        resultsArray: [],
        result: 0,
        points: 0,
        isTimeBased: false,
        resultInput: "",
      },
      {
        name: "Метание мяча",
        resultsArray: [],
        result: 0,
        points: 0,
        isTimeBased: false,
        resultInput: "",
      },
      {
        name: "Бег 500/800м",
        resultsArray: [],
        result: 0,
        points: 0,
        isTimeBased: true,
        resultInput: "",
      },
      {
        name: "Бег 800/1000м",
        resultsArray: [],
        result: 0,
        points: 0,
        isTimeBased: true,
        resultInput: "",
      },
    ],
  };
},
mounted() {
  this.setResultsArrays();
},
watch: {
  gender() {
    this.setResultsArrays();
    this.events.forEach((event) => {
      event.result = 0;
      event.points = 0;
      event.resultInput = "";
    });
  },
},
methods: {
  parseTimeToSeconds(timeStr) {
    // Формат MM:SS,ms (ms — десятые доли секунды)
    if (!timeStr) return null;
    const timeRegex = /^(\d{1,2}):(\d{2}),(\d)$/;
    const match = timeStr.match(timeRegex);
    if (!match) return null;
    const minutes = parseInt(match[1], 10);
    const seconds = parseInt(match[2], 10);
    const tenths = parseInt(match[3], 10);
    if (seconds >= 60) return null;
    return minutes * 60 + seconds + tenths / 10;
  },
  setResultsArrays() {
    if (this.gender === "male") {
      // Бег 30м
      this.events.find(e => e.name === "Бег 30м").resultsArray = [
        { points: 150, result: 4.0 },
        { points: 149, result: 4.1 },
        { points: 148, result: 4.2 },
        { points: 147, result: 4.3 },
        { points: 146, result: 4.4 },
        { points: 145, result: 4.5 },
        { points: 144, result: 4.6 },
        { points: 142, result: 4.7 },
        { points: 140, result: 4.8 },
        { points: 138, result: 4.9 },
        { points: 136, result: 5.0 },
        { points: 133, result: 5.1 },
        { points: 130, result: 5.2 },
        { points: 127, result: 5.3 },
        { points: 124, result: 5.4 },
        { points: 121, result: 5.5 },
        { points: 118, result: 5.6 },
        { points: 115, result: 5.7 },
        { points: 112, result: 5.8 },
        { points: 109, result: 5.9 },
        { points: 106, result: 6.0 },
        { points: 103, result: 6.1 },
        { points: 100, result: 6.2 },
        { points: 97, result: 6.3 },
        { points: 94, result: 6.4 },
        { points: 91, result: 6.5 },
        { points: 88, result: 6.6 },
        { points: 85, result: 6.7 },
        { points: 82, result: 6.8 },
        { points: 79, result: 6.9 },
        { points: 76, result: 7.0 },
        { points: 73, result: 7.1 },
        { points: 70, result: 7.2 },
        { points: 67, result: 7.3 },
        { points: 64, result: 7.4 },
        { points: 61, result: 7.5 },
        { points: 58, result: 7.6 },
        { points: 55, result: 7.7 },
        { points: 52, result: 7.8 },
        { points: 49, result: 7.9 },
        { points: 46, result: 8.0 },
        { points: 43, result: 8.1 },
        { points: 40, result: 8.2 },
        { points: 37, result: 8.3 },
        { points: 34, result: 8.4 },
        { points: 31, result: 8.5 },
        { points: 28, result: 8.6 },
        { points: 25, result: 8.7 },
        { points: 22, result: 8.8 },
        { points: 19, result: 8.9 },
        { points: 16, result: 9.0 },
        { points: 13, result: 9.1 },
        { points: 10, result: 9.2 },
        { points: 7, result: 9.3 },
        { points: 4, result: 9.4 },
        { points: 1, result: 9.5 },
      ].sort((a, b) => a.result - b.result);

      // Прыжки в длину
      this.events.find(e => e.name === "Прыжки в длину").resultsArray = [
        { points: 3, result: 82 },
        { points: 6, result: 83 },
        { points: 9, result: 84 },
        { points: 12, result: 85 },
        { points: 15, result: 86 },
        { points: 18, result: 87 },
        { points: 21, result: 88 },
        { points: 24, result: 89 },
        { points: 27, result: 90 },
        { points: 30, result: 91 },
        { points: 33, result: 92 },
        { points: 36, result: 93 },
        { points: 39, result: 94 },
        { points: 42, result: 95 },
        { points: 45, result: 96 },
        { points: 48, result: 97 },
        { points: 51, result: 98 },
        { points: 52, result: 99 },
        { points: 53, result: 100 },
        { points: 54, result: 101 },
        { points: 55, result: 102 },
        { points: 56, result: 103 },
        { points: 57, result: 104 },
        { points: 58, result: 106 },
        { points: 59, result: 107 },
        { points: 60, result: 108 },
        { points: 61, result: 109 },
        { points: 62, result: 110 },
        { points: 63, result: 111 },
        { points: 64, result: 112 },
        { points: 65, result: 113 },
        { points: 66, result: 114 },
        { points: 67, result: 115 },
        { points: 68, result: 116 },
        { points: 69, result: 117 },
        { points: 70, result: 119 },
        { points: 71, result: 120 },
        { points: 72, result: 121 },
        { points: 73, result: 122 },
        { points: 74, result: 123 },
        { points: 75, result: 124 },
        { points: 76, result: 125 },
        { points: 77, result: 126 },
        { points: 78, result: 127 },
        { points: 79, result: 128 },
        { points: 80, result: 129 },
        { points: 81, result: 130 },
        { points: 82, result: 131 },
        { points: 83, result: 134 },
        { points: 84, result: 135 },
        { points: 85, result: 136 },
        { points: 86, result: 137 },
        { points: 87, result: 138 },
        { points: 88, result: 139 },
        { points: 89, result: 140 },
        { points: 90, result: 141 },
        { points: 91, result: 142 },
        { points: 92, result: 143 },
        { points: 93, result: 144 },
        { points: 94, result: 146 },
        { points: 95, result: 147 },
        { points: 96, result: 148 },
        { points: 97, result: 149 },
        { points: 98, result: 150 },
        { points: 99, result: 151 },
        { points: 100, result: 152 },
        { points: 101, result: 153 },
        { points: 102, result: 155 },
        { points: 103, result: 156 },
        { points: 104, result: 157 },
        { points: 105, result: 158 },
        { points: 106, result: 160 },
        { points: 107, result: 161 },
        { points: 108, result: 162 },
        { points: 109, result: 163 },
        { points: 110, result: 165 },
        { points: 111, result: 166 },
        { points: 112, result: 167 },
        { points: 113, result: 168 },
        { points: 114, result: 170 },
        { points: 115, result: 171 },
        { points: 116, result: 172 },
        { points: 117, result: 173 },
        { points: 118, result: 175 },
        { points: 119, result: 176 },
        { points: 120, result: 177 },
        { points: 121, result: 178 },
        { points: 122, result: 180 },
        { points: 123, result: 181 },
        { points: 124, result: 182 },
        { points: 125, result: 184 },
        { points: 126, result: 185 },
        { points: 127, result: 186 },
        { points: 128, result: 187 },
        { points: 129, result: 189 },
        { points: 130, result: 190 },
        { points: 131, result: 191 },
        { points: 132, result: 192 },
        { points: 133, result: 194 },
        { points: 134, result: 195 },
        { points: 135, result: 196 },
        { points: 136, result: 197 },
        { points: 137, result: 199 },
        { points: 138, result: 200 },
        { points: 139, result: 201 },
        { points: 140, result: 202 },
        { points: 141, result: 204 },
        { points: 142, result: 205 },
        { points: 143, result: 206 },
        { points: 144, result: 207 },
        { points: 145, result: 209 },
        { points: 146, result: 210 },
        { points: 147, result: 211 },
        { points: 148, result: 213 },
        { points: 149, result: 215 },
      ].sort((a, b) => a.result - b.result);

      // Метание мяча
      this.events.find(e => e.name === "Метание мяча").resultsArray = [
        { points: 1, result: 1 },
        { points: 2, result: 2 },
        { points: 3, result: 3 },
        { points: 4, result: 4 },
        { points: 5, result: 5 },
        { points: 6, result: 6 },
        { points: 7, result: 7 },
        { points: 9, result: 9 },
        { points: 11, result: 10 },
        { points: 14, result: 11 },
        { points: 17, result: 12 },
        { points: 20, result: 13 },
        { points: 23, result: 14 },
        { points: 26, result: 15 },
        { points: 29, result: 16 },
        { points: 31, result: 17 },
        { points: 33, result: 18 },
        { points: 35, result: 19 },
        { points: 37, result: 20 },
        { points: 39, result: 21 },
        { points: 41, result: 22 },
        { points: 43, result: 23 },
        { points: 45, result: 24 },
        { points: 47, result: 25 },
        { points: 49, result: 26 },
        { points: 51, result: 27 },
        { points: 53, result: 28 },
        { points: 55, result: 29 },
        { points: 57, result: 30 },
        { points: 59, result: 31 },
        { points: 61, result: 32 },
        { points: 63, result: 33 },
        { points: 65, result: 34 },
        { points: 67, result: 35 },
        { points: 69, result: 36 },
        { points: 71, result: 37 },
        { points: 73, result: 38 },
        { points: 75, result: 39 },
        { points: 77, result: 40 },
        { points: 79, result: 41 },
        { points: 81, result: 42 },
        { points: 83, result: 43 },
        { points: 85, result: 44 },
        { points: 87, result: 45 },
        { points: 89, result: 46 },
        { points: 91, result: 47 },
        { points: 93, result: 48 },
        { points: 95, result: 49 },
        { points: 97, result: 50 },
        { points: 100, result: 51 },
        { points: 103, result: 52 },
        { points: 106, result: 53 },
        { points: 109, result: 54 },
        { points: 112, result: 55 },
        { points: 115, result: 56 },
        { points: 118, result: 57 },
        { points: 121, result: 58 },
        { points: 124, result: 59 },
        { points: 127, result: 60 },
        { points: 130, result: 61 },
        { points: 133, result: 62 },
        { points: 136, result: 63 },
        { points: 139, result: 64 },
        { points: 142, result: 65 },
        { points: 145, result: 66 },
        { points: 148, result: 67 },
        { points: 150, result: 68 },
      ].sort((a, b) => a.result - b.result);

      // Бег 500/800м
      this.events.find(e => e.name === "Бег 500/800м").resultsArray = [
        { points: 150, result: this.parseTimeToSeconds("2:43,1") },
        { points: 149, result: this.parseTimeToSeconds("2:43,2") },
        { points: 148, result: this.parseTimeToSeconds("2:43,3") },
        { points: 147, result: this.parseTimeToSeconds("2:43,4") },
        { points: 146, result: this.parseTimeToSeconds("2:43,5") },
        { points: 145, result: this.parseTimeToSeconds("2:43,6") },
        { points: 144, result: this.parseTimeToSeconds("2:43,7") },
        { points: 143, result: this.parseTimeToSeconds("2:43,8") },
        { points: 142, result: this.parseTimeToSeconds("2:43,9") },
        { points: 141, result: this.parseTimeToSeconds("2:44,0") },
        { points: 140, result: this.parseTimeToSeconds("2:44,1") },
        { points: 139, result: this.parseTimeToSeconds("2:44,2") },
        { points: 138, result: this.parseTimeToSeconds("2:44,3") },
        { points: 137, result: this.parseTimeToSeconds("2:44,4") },
        { points: 136, result: this.parseTimeToSeconds("2:44,5") },
        { points: 135, result: this.parseTimeToSeconds("2:44,6") },
        { points: 134, result: this.parseTimeToSeconds("2:44,7") },
        { points: 133, result: this.parseTimeToSeconds("2:44,8") },
        { points: 132, result: this.parseTimeToSeconds("2:44,9") },
        { points: 131, result: this.parseTimeToSeconds("2:45,0") },
        { points: 130, result: this.parseTimeToSeconds("2:45,1") },
        { points: 129, result: this.parseTimeToSeconds("2:45,2") },
        { points: 128, result: this.parseTimeToSeconds("2:45,3") },
        { points: 127, result: this.parseTimeToSeconds("2:45,4") },
        { points: 126, result: this.parseTimeToSeconds("2:45,5") },
        { points: 125, result: this.parseTimeToSeconds("2:45,6") },
        { points: 124, result: this.parseTimeToSeconds("2:45,7") },
        { points: 123, result: this.parseTimeToSeconds("2:45,8") },
        { points: 122, result: this.parseTimeToSeconds("2:45,9") },
        { points: 121, result: this.parseTimeToSeconds("2:46,0") },
        { points: 120, result: this.parseTimeToSeconds("2:46,1") },
        { points: 119, result: this.parseTimeToSeconds("2:46,2") },
        { points: 118, result: this.parseTimeToSeconds("2:46,3") },
        { points: 117, result: this.parseTimeToSeconds("2:46,4") },
        { points: 116, result: this.parseTimeToSeconds("2:46,5") },
        { points: 115, result: this.parseTimeToSeconds("2:46,6") },
        { points: 114, result: this.parseTimeToSeconds("2:46,7") },
        { points: 113, result: this.parseTimeToSeconds("2:46,8") },
        { points: 112, result: this.parseTimeToSeconds("2:46,9") },
        { points: 111, result: this.parseTimeToSeconds("2:47,0") },
        { points: 110, result: this.parseTimeToSeconds("2:47,1") },
        { points: 109, result: this.parseTimeToSeconds("2:47,2") },
        { points: 108, result: this.parseTimeToSeconds("2:47,3") },
        { points: 107, result: this.parseTimeToSeconds("2:47,4") },
        { points: 106, result: this.parseTimeToSeconds("2:47,5") },
        { points: 105, result: this.parseTimeToSeconds("2:47,6") },
        { points: 104, result: this.parseTimeToSeconds("2:47,7") },
        { points: 103, result: this.parseTimeToSeconds("2:47,8") },
        { points: 102, result: this.parseTimeToSeconds("2:47,9") },
        { points: 101, result: this.parseTimeToSeconds("2:48,0") },
        { points: 100, result: this.parseTimeToSeconds("2:48,1") },
        { points: 99, result: this.parseTimeToSeconds("2:48,2") },
        { points: 98, result: this.parseTimeToSeconds("2:48,3") },
        { points: 97, result: this.parseTimeToSeconds("2:48,4") },
        { points: 96, result: this.parseTimeToSeconds("2:48,5") },
        { points: 95, result: this.parseTimeToSeconds("2:48,6") },
        { points: 94, result: this.parseTimeToSeconds("2:48,7") },
        { points: 93, result: this.parseTimeToSeconds("2:48,8") },
        { points: 92, result: this.parseTimeToSeconds("2:48,9") },
        { points: 91, result: this.parseTimeToSeconds("2:49,0") },
        { points: 90, result: this.parseTimeToSeconds("2:49,1") },
        { points: 89, result: this.parseTimeToSeconds("2:49,2") },
        { points: 88, result: this.parseTimeToSeconds("2:49,3") },
        { points: 87, result: this.parseTimeToSeconds("2:49,4") },
        { points: 86, result: this.parseTimeToSeconds("2:49,5") },
        { points: 85, result: this.parseTimeToSeconds("2:49,6") },
        { points: 84, result: this.parseTimeToSeconds("2:49,7") },
        { points: 83, result: this.parseTimeToSeconds("2:49,9") },
        { points: 82, result: this.parseTimeToSeconds("2:50,0") },
        { points: 81, result: this.parseTimeToSeconds("2:50,4") },
        { points: 80, result: this.parseTimeToSeconds("2:50,8") },
        { points: 79, result: this.parseTimeToSeconds("2:51,2") },
        { points: 78, result: this.parseTimeToSeconds("2:51,6") },
        { points: 77, result: this.parseTimeToSeconds("2:52,0") },
        { points: 76, result: this.parseTimeToSeconds("2:52,4") },
        { points: 75, result: this.parseTimeToSeconds("2:52,8") },
        { points: 74, result: this.parseTimeToSeconds("2:53,2") },
        { points: 73, result: this.parseTimeToSeconds("2:53,7") },
        { points: 72, result: this.parseTimeToSeconds("2:54,2") },
        { points: 71, result: this.parseTimeToSeconds("2:54,7") },
        { points: 70, result: this.parseTimeToSeconds("2:55,2") },
        { points: 69, result: this.parseTimeToSeconds("2:55,7") },
        { points: 68, result: this.parseTimeToSeconds("2:56,2") },
        { points: 67, result: this.parseTimeToSeconds("2:56,7") },
        { points: 66, result: this.parseTimeToSeconds("2:57,2") },
        { points: 65, result: this.parseTimeToSeconds("2:58,2") },
        { points: 64, result: this.parseTimeToSeconds("3:01,2") },
        { points: 63, result: this.parseTimeToSeconds("3:02,4") },
        { points: 62, result: this.parseTimeToSeconds("3:03,7") },
        { points: 61, result: this.parseTimeToSeconds("3:05,0") },
        { points: 60, result: this.parseTimeToSeconds("3:06,3") },
        { points: 59, result: this.parseTimeToSeconds("3:07,6") },
        { points: 58, result: this.parseTimeToSeconds("3:08,9") },
        { points: 57, result: this.parseTimeToSeconds("3:10,2") },
        { points: 56, result: this.parseTimeToSeconds("3:11,5") },
        { points: 55, result: this.parseTimeToSeconds("3:13,8") },
        { points: 54, result: this.parseTimeToSeconds("3:15,2") },
        { points: 53, result: this.parseTimeToSeconds("3:16,6") },
        { points: 52, result: this.parseTimeToSeconds("3:18,0") },
        { points: 51, result: this.parseTimeToSeconds("3:20,5") },
        { points: 50, result: this.parseTimeToSeconds("3:22,0") },
        { points: 49, result: this.parseTimeToSeconds("3:23,5") },
        { points: 48, result: this.parseTimeToSeconds("3:26,1") },
        { points: 47, result: this.parseTimeToSeconds("3:27,7") },
        { points: 46, result: this.parseTimeToSeconds("3:30,3") },
        { points: 45, result: this.parseTimeToSeconds("3:32,0") },
        { points: 44, result: this.parseTimeToSeconds("3:33,8") },
        { points: 43, result: this.parseTimeToSeconds("3:37,7") },
        { points: 42, result: this.parseTimeToSeconds("3:39,7") },
        { points: 41, result: this.parseTimeToSeconds("3:41,7") },
        { points: 40, result: this.parseTimeToSeconds("3:45,8") },
        { points: 39, result: this.parseTimeToSeconds("3:47,9") },
        { points: 38, result: this.parseTimeToSeconds("3:53,0") },
        { points: 37, result: this.parseTimeToSeconds("3:55,1") },
        { points: 36, result: this.parseTimeToSeconds("3:57,2") },
        { points: 35, result: this.parseTimeToSeconds("4:01,3") },
        { points: 34, result: this.parseTimeToSeconds("4:03,4") },
        { points: 33, result: this.parseTimeToSeconds("4:05,6") },
        { points: 32, result: this.parseTimeToSeconds("4:09,0") },
        { points: 31, result: this.parseTimeToSeconds("4:12,3") },
        { points: 30, result: this.parseTimeToSeconds("4:14,8") },
        { points: 29, result: this.parseTimeToSeconds("4:19,4") },
        { points: 28, result: this.parseTimeToSeconds("4:22,1") },
        { points: 27, result: this.parseTimeToSeconds("4:24,8") },
        { points: 26, result: this.parseTimeToSeconds("4:30,6") },
        { points: 25, result: this.parseTimeToSeconds("4:33,3") },
        { points: 24, result: this.parseTimeToSeconds("4:36,0") },
        { points: 23, result: this.parseTimeToSeconds("4:40,8") },
        { points: 22, result: this.parseTimeToSeconds("4:43,5") },
        { points: 21, result: this.parseTimeToSeconds("4:46,2") },
        { points: 20, result: this.parseTimeToSeconds("4:53,9") },
        { points: 19, result: this.parseTimeToSeconds("4:56,7") },
        { points: 18, result: this.parseTimeToSeconds("4:59,4") },
        { points: 17, result: this.parseTimeToSeconds("5:02,1") },
        { points: 16, result: this.parseTimeToSeconds("5:02,5") },
        { points: 15, result: this.parseTimeToSeconds("5:03,0") },
        { points: 14, result: this.parseTimeToSeconds("5:03,5") },
        { points: 13, result: this.parseTimeToSeconds("5:04,0") },
        { points: 12, result: this.parseTimeToSeconds("5:04,5") },
        { points: 11, result: this.parseTimeToSeconds("5:05,0") },
        { points: 10, result: this.parseTimeToSeconds("5:05,5") },
        { points: 9, result: this.parseTimeToSeconds("5:06,0") },
        { points: 8, result: this.parseTimeToSeconds("5:06,5") },
        { points: 7, result: this.parseTimeToSeconds("5:07,0") },
        { points: 6, result: this.parseTimeToSeconds("5:07,5") },
        { points: 5, result: this.parseTimeToSeconds("5:08,0") },
        { points: 4, result: this.parseTimeToSeconds("5:08,5") },
        { points: 3, result: this.parseTimeToSeconds("5:09,0") },
        { points: 2, result: this.parseTimeToSeconds("5:10,0") },
        { points: 1, result: this.parseTimeToSeconds("5:12,0") },
      ].sort((a, b) => a.result - b.result);

      // Бег 800/1000м — примерные данные (можно заменить на реальные)
      this.events.find(e => e.name === "Бег 800/1000м").resultsArray = [
        { points: 150, result: this.parseTimeToSeconds("3:15,0") },
        { points: 149, result: this.parseTimeToSeconds("3:17,0") },
        { points: 148, result: this.parseTimeToSeconds("3:19,5") },
        { points: 147, result: this.parseTimeToSeconds("3:22,0") },
        { points: 146, result: this.parseTimeToSeconds("3:24,5") },
        { points: 145, result: this.parseTimeToSeconds("3:27,0") },
        { points: 144, result: this.parseTimeToSeconds("3:29,5") },
        { points: 143, result: this.parseTimeToSeconds("3:32,0") },
        { points: 142, result: this.parseTimeToSeconds("3:34,5") },
        { points: 141, result: this.parseTimeToSeconds("3:37,0") },
        { points: 140, result: this.parseTimeToSeconds("3:39,5") },
        { points: 139, result: this.parseTimeToSeconds("3:42,0") },
        { points: 138, result: this.parseTimeToSeconds("3:44,5") },
        { points: 137, result: this.parseTimeToSeconds("3:47,0") },
        { points: 136, result: this.parseTimeToSeconds("3:49,5") },
        { points: 135, result: this.parseTimeToSeconds("3:52,0") },
        { points: 134, result: this.parseTimeToSeconds("3:54,5") },
        { points: 133, result: this.parseTimeToSeconds("3:57,0") },
        { points: 132, result: this.parseTimeToSeconds("3:59,5") },
        { points: 131, result: this.parseTimeToSeconds("4:02,0") },
        { points: 130, result: this.parseTimeToSeconds("4:04,5") },
        { points: 129, result: this.parseTimeToSeconds("4:07,0") },
        { points: 128, result: this.parseTimeToSeconds("4:09,5") },
        { points: 127, result: this.parseTimeToSeconds("4:12,0") },
        { points: 126, result: this.parseTimeToSeconds("4:14,5") },
        { points: 125, result: this.parseTimeToSeconds("4:17,0") },
        { points: 124, result: this.parseTimeToSeconds("4:19,5") },
        { points: 123, result: this.parseTimeToSeconds("4:22,0") },
        { points: 122, result: this.parseTimeToSeconds("4:24,5") },
        { points: 121, result: this.parseTimeToSeconds("4:27,0") },
        { points: 120, result: this.parseTimeToSeconds("4:29,5") },
        { points: 119, result: this.parseTimeToSeconds("4:32,0") },
        { points: 118, result: this.parseTimeToSeconds("4:34,5") },
        { points: 117, result: this.parseTimeToSeconds("4:37,0") },
        { points: 116, result: this.parseTimeToSeconds("4:39,5") },
        { points: 115, result: this.parseTimeToSeconds("4:42,0") },
        { points: 114, result: this.parseTimeToSeconds("4:44,5") },
        { points: 113, result: this.parseTimeToSeconds("4:47,0") },
        { points: 112, result: this.parseTimeToSeconds("4:49,5") },
        { points: 111, result: this.parseTimeToSeconds("4:52,0") },
        { points: 110, result: this.parseTimeToSeconds("4:54,5") },
        { points: 109, result: this.parseTimeToSeconds("4:57,0") },
        { points: 108, result: this.parseTimeToSeconds("4:59,5") },
        { points: 107, result: this.parseTimeToSeconds("5:02,0") },
        { points: 106, result: this.parseTimeToSeconds("5:04,5") },
        { points: 105, result: this.parseTimeToSeconds("5:07,0") },
        { points: 104, result: this.parseTimeToSeconds("5:10,7") },
        { points: 103, result: this.parseTimeToSeconds("5:14,4") },
        { points: 102, result: this.parseTimeToSeconds("5:18,1") },
        { points: 101, result: this.parseTimeToSeconds("5:21,8") },
        { points: 100, result: this.parseTimeToSeconds("5:25,5") },
        { points: 99, result: this.parseTimeToSeconds("5:29,2") },
        { points: 98, result: this.parseTimeToSeconds("5:32,9") },
        { points: 97, result: this.parseTimeToSeconds("5:36,6") },
        { points: 96, result: this.parseTimeToSeconds("5:40,0") },
        { points: 95, result: this.parseTimeToSeconds("5:44,0") },
        { points: 94, result: this.parseTimeToSeconds("5:47,2") },
        { points: 93, result: this.parseTimeToSeconds("5:50,4") },
        { points: 92, result: this.parseTimeToSeconds("5:53,6") },
        { points: 91, result: this.parseTimeToSeconds("5:56,8") },
        { points: 90, result: this.parseTimeToSeconds("6:00,0") },
        { points: 89, result: this.parseTimeToSeconds("6:03,2") },
        { points: 88, result: this.parseTimeToSeconds("6:06,4") },
        { points: 87, result: this.parseTimeToSeconds("6:09,6") },
        { points: 86, result: this.parseTimeToSeconds("6:12,8") },
        { points: 85, result: this.parseTimeToSeconds("6:16,0") },
        { points: 84, result: this.parseTimeToSeconds("6:19,2") },
        { points: 83, result: this.parseTimeToSeconds("6:22,4") },
        { points: 82, result: this.parseTimeToSeconds("6:25,6") },
        { points: 81, result: this.parseTimeToSeconds("6:28,8") },
        { points: 80, result: this.parseTimeToSeconds("6:32,0") },
        { points: 79, result: this.parseTimeToSeconds("6:35,2") },
        { points: 78, result: this.parseTimeToSeconds("6:35,8") },
        { points: 77, result: this.parseTimeToSeconds("6:36,4") },
        { points: 76, result: this.parseTimeToSeconds("6:37,0") },
        { points: 75, result: this.parseTimeToSeconds("6:37,6") },
        { points: 74, result: this.parseTimeToSeconds("6:38,2") },
        { points: 73, result: this.parseTimeToSeconds("6:38,8") },
        { points: 72, result: this.parseTimeToSeconds("6:39,4") },
        { points: 71, result: this.parseTimeToSeconds("6:40,0") },
        { points: 70, result: this.parseTimeToSeconds("6:40,6") },
        { points: 69, result: this.parseTimeToSeconds("6:41,2") },
        { points: 68, result: this.parseTimeToSeconds("6:41,8") },
        { points: 67, result: this.parseTimeToSeconds("6:42,4") },
        { points: 66, result: this.parseTimeToSeconds("6:43,0") },
        { points: 65, result: this.parseTimeToSeconds("6:44,6") },
        { points: 64, result: this.parseTimeToSeconds("6:44,2") },
        { points: 63, result: this.parseTimeToSeconds("6:44,8") },
        { points: 62, result: this.parseTimeToSeconds("6:45,4") },
        { points: 61, result: this.parseTimeToSeconds("6:46,0") },
        { points: 60, result: this.parseTimeToSeconds("6:46,6") },
        { points: 59, result: this.parseTimeToSeconds("6:47,2") },
        { points: 58, result: this.parseTimeToSeconds("6:47,8") },
        { points: 57, result: this.parseTimeToSeconds("6:48,4") },
        { points: 56, result: this.parseTimeToSeconds("6:49,0") },
        { points: 55, result: this.parseTimeToSeconds("6:49,6") },
        { points: 54, result: this.parseTimeToSeconds("6:50,2") },
        { points: 53, result: this.parseTimeToSeconds("6:50,8") },
        { points: 52, result: this.parseTimeToSeconds("6:51,4") },
        { points: 51, result: this.parseTimeToSeconds("6:52,0") },
        { points: 50, result: this.parseTimeToSeconds("6:52,6") },
        { points: 49, result: this.parseTimeToSeconds("6:53,2") },
        { points: 48, result: this.parseTimeToSeconds("6:53,8") },
        { points: 47, result: this.parseTimeToSeconds("6:54,4") },
        { points: 46, result: this.parseTimeToSeconds("6:55,0") },
        { points: 45, result: this.parseTimeToSeconds("6:55,6") },
        { points: 44, result: this.parseTimeToSeconds("6:56,2") },
        { points: 43, result: this.parseTimeToSeconds("6:56,8") },
        { points: 42, result: this.parseTimeToSeconds("6:57,4") },
        { points: 41, result: this.parseTimeToSeconds("6:58,0") },
        { points: 40, result: this.parseTimeToSeconds("6:58,6") },
        { points: 39, result: this.parseTimeToSeconds("6:59,2") },
        { points: 38, result: this.parseTimeToSeconds("6:59,8") },
        { points: 37, result: this.parseTimeToSeconds("7:00,4") },
        { points: 36, result: this.parseTimeToSeconds("7:01,0") },
        { points: 35, result: this.parseTimeToSeconds("7:01,6") },
        { points: 34, result: this.parseTimeToSeconds("7:02,2") },
        { points: 33, result: this.parseTimeToSeconds("7:02,8") },
        { points: 32, result: this.parseTimeToSeconds("7:03,4") },
        { points: 31, result: this.parseTimeToSeconds("7:04,0") },
        { points: 30, result: this.parseTimeToSeconds("7:04,6") },
        { points: 29, result: this.parseTimeToSeconds("7:05,2") },
        { points: 28, result: this.parseTimeToSeconds("7:05,8") },
        { points: 27, result: this.parseTimeToSeconds("7:06,4") },
        { points: 26, result: this.parseTimeToSeconds("7:07,0") },
        { points: 25, result: this.parseTimeToSeconds("7:07,6") },
        { points: 24, result: this.parseTimeToSeconds("7:08,2") },
        { points: 23, result: this.parseTimeToSeconds("7:08,8") },
        { points: 22, result: this.parseTimeToSeconds("7:09,4") },
        { points: 21, result: this.parseTimeToSeconds("7:10,0") },
        { points: 20, result: this.parseTimeToSeconds("7:10,6") },
        { points: 19, result: this.parseTimeToSeconds("7:11,2") },
        { points: 18, result: this.parseTimeToSeconds("7:11,8") },
        { points: 17, result: this.parseTimeToSeconds("7:12,4") },
        { points: 16, result: this.parseTimeToSeconds("7:13,0") },
        { points: 15, result: this.parseTimeToSeconds("7:13,6") },
        { points: 14, result: this.parseTimeToSeconds("7:14,2") },
        { points: 13, result: this.parseTimeToSeconds("7:14,8") },
        { points: 12, result: this.parseTimeToSeconds("7:15,4") },
        { points: 11, result: this.parseTimeToSeconds("7:16,0") },
        { points: 10, result: this.parseTimeToSeconds("7:16,6") },
        { points: 9, result: this.parseTimeToSeconds("7:17,2") },
        { points: 8, result: this.parseTimeToSeconds("7:17,8") },
        { points: 7, result: this.parseTimeToSeconds("7:18,4") },
        { points: 6, result: this.parseTimeToSeconds("7:19,0") },
        { points: 5, result: this.parseTimeToSeconds("7:19,6") },
        { points: 4, result: this.parseTimeToSeconds("7:20,2") },
        { points: 3, result: this.parseTimeToSeconds("7:20,8") },
        { points: 2, result: this.parseTimeToSeconds("7:21,4") },
        { points: 1, result: this.parseTimeToSeconds("7:22,0") },
      ].sort((a, b) => a.result - b.result);

    } else {
      // Женский пол - аналогично, можно заполнить по вашим данным
      this.events.find(e => e.name === "Бег 30м").resultsArray = [
        { points: 150, result: 4.4 },
        { points: 149, result: 4.5 },
        { points: 148, result: 4.6 },
        { points: 147, result: 4.7 },
        { points: 146, result: 4.8 },
        { points: 145, result: 4.9 },
        { points: 144, result: 5.0 },
        { points: 142, result: 5.1 },
        { points: 140, result: 5.2 },
        { points: 138, result: 5.3 },
        { points: 136, result: 5.4 },
        { points: 133, result: 5.5 },
        { points: 130, result: 5.6 },
        { points: 127, result: 5.7 },
        { points: 124, result: 5.8 },
        { points: 121, result: 5.9 },
        { points: 118, result: 6.0 },
        { points: 115, result: 6.1 },
        { points: 112, result: 6.2 },
        { points: 109, result: 6.3 },
        { points: 106, result: 6.4 },
        { points: 103, result: 6.5 },
        { points: 100, result: 6.6 },
        { points: 97, result: 6.7 },
        { points: 94, result: 6.8 },
        { points: 91, result: 6.9 },
        { points: 88, result: 7.0 },
        { points: 85, result: 7.1 },
        { points: 82, result: 7.2 },
        { points: 79, result: 7.3 },
        { points: 76, result: 7.4 },
        { points: 73, result: 7.5 },
        { points: 70, result: 7.6 },
        { points: 67, result: 7.7 },
        { points: 64, result: 7.8 },
        { points: 61, result: 7.9 },
        { points: 58, result: 8.0 },
        { points: 55, result: 8.1 },
        { points: 52, result: 8.2 },
        { points: 49, result: 8.3 },
        { points: 46, result: 8.4 },
        { points: 43, result: 8.5 },
        { points: 40, result: 8.6 },
        { points: 37, result: 8.7 },
        { points: 34, result: 8.8 },
        { points: 31, result: 8.9 },
        { points: 28, result: 9.0 },
        { points: 25, result: 9.1 },
        { points: 22, result: 9.2 },
        { points: 19, result: 9.3 },
        { points: 16, result: 9.4 },
        { points: 13, result: 9.5 },
        { points: 10, result: 9.6 },
        { points: 7, result: 9.7 },
        { points: 4, result: 9.8 },
        { points: 1, result: 9.9 },
      ].sort((a, b) => a.result - b.result);
// Прыжки в длину
      this.events.find(e => e.name === "Прыжки в длину").resultsArray = [
      { points: 3, result: 73 },
{ points: 6, result: 74 },
{ points: 9, result: 75 },
{ points: 12, result: 76 },
{ points: 15, result: 77 },
{ points: 18, result: 78 },
{ points: 21, result: 79 },
{ points: 24, result: 80 },
{ points: 27, result: 81 },
{ points: 30, result: 82 },
{ points: 33, result: 83 },
{ points: 36, result: 84 },
{ points: 39, result: 85 },
{ points: 42, result: 86 },
{ points: 45, result: 87 },
{ points: 48, result: 88 },
{ points: 51, result: 89 },
{ points: 52, result: 90 },
{ points: 53, result: 91 },
{ points: 54, result: 92 },
{ points: 55, result: 93 },
{ points: 56, result: 94 },
{ points: 57, result: 95 },
{ points: 58, result: 96 },
{ points: 59, result: 97 },
{ points: 60, result: 98 },
{ points: 61, result: 99 },
{ points: 62, result: 100 },
{ points: 63, result: 101 },
{ points: 64, result: 102 },
{ points: 65, result: 103 },
{ points: 66, result: 104 },
{ points: 67, result: 105 },
{ points: 68, result: 106 },
{ points: 69, result: 107 },
{ points: 70, result: 108 },
{ points: 71, result: 110 },
{ points: 72, result: 111 },
{ points: 73, result: 112 },
{ points: 74, result: 113 },
{ points: 75, result: 114 },
{ points: 76, result: 115 },
{ points: 77, result: 116 },
{ points: 78, result: 117 },
{ points: 79, result: 118 },
{ points: 81, result: 119 },
{ points: 82, result: 120 },
{ points: 83, result: 121 },
{ points: 84, result: 122 },
{ points: 85, result: 123 },
{ points: 86, result: 124 },
{ points: 87, result: 125 },
{ points: 88, result: 126 },
{ points: 89, result: 127 },
{ points: 90, result: 128 },
{ points: 91, result: 129 },
{ points: 92, result: 131 },
{ points: 93, result: 132 },
{ points: 94, result: 133 },
{ points: 95, result: 134 },
{ points: 97, result: 137 },
{ points: 98, result: 138 },
{ points: 99, result: 139 },
{ points: 100, result: 140 },
{ points: 101, result: 141 },
{ points: 102, result: 142 },
{ points: 103, result: 143 },
{ points: 104, result: 145 },
{ points: 105, result: 146 },
{ points: 106, result: 147 },
{ points: 107, result: 148 },
{ points: 108, result: 150 },
{ points: 109, result: 151 },
{ points: 110, result: 152 },
{ points: 111, result: 153 },
{ points: 112, result: 154 },
{ points: 113, result: 156 },
{ points: 114, result: 157 },
{ points: 115, result: 158 },
{ points: 116, result: 159 },
{ points: 117, result: 161 },
{ points: 118, result: 162 },
{ points: 119, result: 163 },
{ points: 120, result: 164 },
{ points: 121, result: 166 },
{ points: 122, result: 167 },
{ points: 123, result: 168 },
{ points: 124, result: 169 },
{ points: 125, result: 170 },
{ points: 126, result: 172 },
{ points: 127, result: 173 },
{ points: 128, result: 174 },
{ points: 129, result: 175 },
{ points: 130, result: 177 },
{ points: 131, result: 178 },
{ points: 132, result: 179 },
{ points: 133, result: 180 },
{ points: 134, result: 181 },
{ points: 135, result: 183 },
{ points: 136, result: 184 },
{ points: 137, result: 185 },
{ points: 138, result: 186 },
{ points: 139, result: 188 },
{ points: 140, result: 189 },
{ points: 141, result: 190 },
{ points: 142, result: 191 },
{ points: 143, result: 192 },
{ points: 144, result: 194 },
{ points: 145, result: 195 },
{ points: 146, result: 196 },
{ points: 147, result: 197 },
{ points: 148, result: 199 },
{ points: 149, result: 200 },
{ points: 150, result: 201 },
      ].sort((a, b) => a.result - b.result);

      // Метание мяча
      this.events.find(e => e.name === "Метание мяча").resultsArray = [
      { points: 2, result: 1 },
      { points: 5, result: 2 },
      { points: 11, result: 4 },
      { points: 18, result: 6 },
      { points: 21, result: 7 },
      { points: 24, result: 8 },
      { points: 27, result: 9 },
      { points: 30, result: 10 },
      { points: 33, result: 11 },
      { points: 36, result: 12 },
      { points: 39, result: 13 },
      { points: 42, result: 14 },
      { points: 45, result: 15 },
      { points: 48, result: 16 },
      { points: 51, result: 17 },
      { points: 54, result: 18 },
      { points: 57, result: 19 },
      { points: 60, result: 20 },
      { points: 63, result: 21 },
      { points: 66, result: 22 },
      { points: 70, result: 23 },
      { points: 73, result: 24 },
      { points: 75, result: 25 },
      { points: 78, result: 26 },
      { points: 80, result: 27 },
      { points: 83, result: 28 },
      { points: 86, result: 29 },
      { points: 88, result: 30 },
      { points: 91, result: 31 },
      { points: 93, result: 32 },
      { points: 96, result: 33 },
      { points: 99, result: 34 },
      { points: 101, result: 35 },
      { points: 104, result: 36 },
      { points: 106, result: 37 },
      { points: 109, result: 38 },
      { points: 111, result: 39 },
      { points: 113, result: 40 },
      { points: 116, result: 41 },
      { points: 118, result: 42 },
      { points: 121, result: 43 },
      { points: 124, result: 44 },
      { points: 127, result: 45 },
      { points: 130, result: 46 },
      { points: 133, result: 47 },
      { points: 136, result: 48 },
      { points: 139, result: 49 },
      { points: 142, result: 50 },
      { points: 145, result: 51 },
      { points: 148, result: 52 },
      { points: 150, result: 53 },
      ].sort((a, b) => a.result - b.result);

      // Бег 500/800м
      this.events.find(e => e.name === "Бег 500/800м").resultsArray = [
        { points: 150, result: this.parseTimeToSeconds("1:45,9") },
{ points: 149, result: this.parseTimeToSeconds("1:46,0") },
{ points: 148, result: this.parseTimeToSeconds("1:46,1") },
{ points: 147, result: this.parseTimeToSeconds("1:46,2") },
{ points: 146, result: this.parseTimeToSeconds("1:46,3") },
{ points: 145, result: this.parseTimeToSeconds("1:46,4") },
{ points: 144, result: this.parseTimeToSeconds("1:46,5") },
{ points: 143, result: this.parseTimeToSeconds("1:46,6") },
{ points: 142, result: this.parseTimeToSeconds("1:46,7") },
{ points: 141, result: this.parseTimeToSeconds("1:46,8") },
{ points: 140, result: this.parseTimeToSeconds("1:46,9") },
{ points: 139, result: this.parseTimeToSeconds("1:47,0") },
{ points: 138, result: this.parseTimeToSeconds("1:47,1") },
{ points: 137, result: this.parseTimeToSeconds("1:47,2") },
{ points: 136, result: this.parseTimeToSeconds("1:47,3") },
{ points: 135, result: this.parseTimeToSeconds("1:47,4") },
{ points: 134, result: this.parseTimeToSeconds("1:47,5") },
{ points: 133, result: this.parseTimeToSeconds("1:47,6") },
{ points: 132, result: this.parseTimeToSeconds("1:47,7") },
{ points: 131, result: this.parseTimeToSeconds("1:47,8") },
{ points: 130, result: this.parseTimeToSeconds("1:47,9") },
{ points: 129, result: this.parseTimeToSeconds("1:48,0") },
{ points: 128, result: this.parseTimeToSeconds("1:48,1") },
{ points: 127, result: this.parseTimeToSeconds("1:48,2") },
{ points: 126, result: this.parseTimeToSeconds("1:48,3") },
{ points: 125, result: this.parseTimeToSeconds("1:48,4") },
{ points: 124, result: this.parseTimeToSeconds("1:48,5") },
{ points: 123, result: this.parseTimeToSeconds("1:48,6") },
{ points: 122, result: this.parseTimeToSeconds("1:48,7") },
{ points: 121, result: this.parseTimeToSeconds("1:48,8") },
{ points: 120, result: this.parseTimeToSeconds("1:48,9") },
{ points: 119, result: this.parseTimeToSeconds("1:49,0") },
{ points: 118, result: this.parseTimeToSeconds("1:49,1") },
{ points: 117, result: this.parseTimeToSeconds("1:49,2") },
{ points: 116, result: this.parseTimeToSeconds("1:49,3") },
{ points: 115, result: this.parseTimeToSeconds("1:49,4") },
{ points: 114, result: this.parseTimeToSeconds("1:49,5") },
{ points: 113, result: this.parseTimeToSeconds("1:49,6") },
{ points: 112, result: this.parseTimeToSeconds("1:49,7") },
{ points: 111, result: this.parseTimeToSeconds("1:49,8") },
{ points: 110, result: this.parseTimeToSeconds("1:49,9") },
{ points: 109, result: this.parseTimeToSeconds("1:50,0") },
{ points: 108, result: this.parseTimeToSeconds("1:50,1") },
{ points: 107, result: this.parseTimeToSeconds("1:50,2") },
{ points: 106, result: this.parseTimeToSeconds("1:50,3") },
{ points: 105, result: this.parseTimeToSeconds("1:50,4") },
{ points: 104, result: this.parseTimeToSeconds("1:50,5") },
{ points: 103, result: this.parseTimeToSeconds("1:50,6") },
{ points: 102, result: this.parseTimeToSeconds("1:50,7") },
{ points: 101, result: this.parseTimeToSeconds("1:50,8") },
{ points: 100, result: this.parseTimeToSeconds("1:50,9") },
{ points: 99, result: this.parseTimeToSeconds("1:51,0") },
{ points: 98, result: this.parseTimeToSeconds("1:51,1") },
{ points: 97, result: this.parseTimeToSeconds("1:51,2") },
{ points: 96, result: this.parseTimeToSeconds("1:51,3") },
{ points: 95, result: this.parseTimeToSeconds("1:51,6") },
{ points: 94, result: this.parseTimeToSeconds("1:51,9") },
{ points: 93, result: this.parseTimeToSeconds("1:52,4") },
{ points: 92, result: this.parseTimeToSeconds("1:52,8") },
{ points: 91, result: this.parseTimeToSeconds("1:53,2") },
{ points: 90, result: this.parseTimeToSeconds("1:53,6") },
{ points: 89, result: this.parseTimeToSeconds("1:54,0") },
{ points: 88, result: this.parseTimeToSeconds("1:54,4") },
{ points: 87, result: this.parseTimeToSeconds("1:54,8") },
{ points: 86, result: this.parseTimeToSeconds("1:55,2") },
{ points: 85, result: this.parseTimeToSeconds("1:55,6") },
{ points: 84, result: this.parseTimeToSeconds("1:56,0") },
{ points: 83, result: this.parseTimeToSeconds("1:56,5") },
{ points: 82, result: this.parseTimeToSeconds("1:57,0") },
{ points: 81, result: this.parseTimeToSeconds("1:57,5") },
{ points: 80, result: this.parseTimeToSeconds("1:58,0") },
{ points: 79, result: this.parseTimeToSeconds("1:58,5") },
{ points: 78, result: this.parseTimeToSeconds("1:59,0") },
{ points: 77, result: this.parseTimeToSeconds("1:59,5") },
{ points: 76, result: this.parseTimeToSeconds("2:00,0") },
{ points: 75, result: this.parseTimeToSeconds("2:02,0") },
{ points: 74, result: this.parseTimeToSeconds("2:04,0") },
{ points: 73, result: this.parseTimeToSeconds("2:06,0") },
{ points: 72, result: this.parseTimeToSeconds("2:08,0") },
{ points: 71, result: this.parseTimeToSeconds("2:10,0") },
{ points: 70, result: this.parseTimeToSeconds("2:12,0") },
{ points: 69, result: this.parseTimeToSeconds("2:14,0") },
{ points: 68, result: this.parseTimeToSeconds("2:16,0") },
{ points: 67, result: this.parseTimeToSeconds("2:18,0") },
{ points: 66, result: this.parseTimeToSeconds("2:20,5") },
{ points: 65, result: this.parseTimeToSeconds("2:23,0") },
{ points: 64, result: this.parseTimeToSeconds("2:25,5") },
{ points: 63, result: this.parseTimeToSeconds("2:28,0") },
{ points: 62, result: this.parseTimeToSeconds("2:30,5") },
{ points: 61, result: this.parseTimeToSeconds("2:33,0") },
{ points: 60, result: this.parseTimeToSeconds("2:35,5") },
{ points: 59, result: this.parseTimeToSeconds("2:38,0") },
{ points: 58, result: this.parseTimeToSeconds("2:40,5") },
{ points: 57, result: this.parseTimeToSeconds("2:41,0") },
{ points: 56, result: this.parseTimeToSeconds("2:41,5") },
{ points: 55, result: this.parseTimeToSeconds("2:42,0") },
{ points: 54, result: this.parseTimeToSeconds("2:42,5") },
{ points: 53, result: this.parseTimeToSeconds("2:43,0") },
{ points: 52, result: this.parseTimeToSeconds("2:43,5") },
{ points: 51, result: this.parseTimeToSeconds("2:44,0") },
{ points: 50, result: this.parseTimeToSeconds("2:44,5") },
{ points: 49, result: this.parseTimeToSeconds("2:45,5") },
{ points: 48, result: this.parseTimeToSeconds("2:46,0") },
{ points: 47, result: this.parseTimeToSeconds("2:46,5") },
{ points: 46, result: this.parseTimeToSeconds("2:47,0") },
{ points: 45, result: this.parseTimeToSeconds("2:47,5") },
{ points: 44, result: this.parseTimeToSeconds("2:48,0") },
{ points: 43, result: this.parseTimeToSeconds("2:48,5") },
{ points: 42, result: this.parseTimeToSeconds("2:49,0") },
{ points: 41, result: this.parseTimeToSeconds("2:51,5") },
{ points: 40, result: this.parseTimeToSeconds("2:54,5") },
{ points: 39, result: this.parseTimeToSeconds("2:57,5") },
{ points: 38, result: this.parseTimeToSeconds("3:00,5") },
{ points: 37, result: this.parseTimeToSeconds("3:03,5") },
{ points: 36, result: this.parseTimeToSeconds("3:06,5") },
{ points: 35, result: this.parseTimeToSeconds("3:09,5") },
{ points: 34, result: this.parseTimeToSeconds("3:12,5") },
{ points: 33, result: this.parseTimeToSeconds("3:13,0") },
{ points: 32, result: this.parseTimeToSeconds("3:14,0") },
{ points: 31, result: this.parseTimeToSeconds("3:15,0") },
{ points: 30, result: this.parseTimeToSeconds("3:15,5") },
{ points: 29, result: this.parseTimeToSeconds("3:19,0") },
{ points: 28, result: this.parseTimeToSeconds("3:22,5") },
{ points: 27, result: this.parseTimeToSeconds("3:26,0") },
{ points: 26, result: this.parseTimeToSeconds("3:29,5") },
{ points: 25, result: this.parseTimeToSeconds("3:33,0") },
{ points: 24, result: this.parseTimeToSeconds("3:36,5") },
{ points: 23, result: this.parseTimeToSeconds("3:40,0") },
{ points: 22, result: this.parseTimeToSeconds("3:43,5") },
{ points: 21, result: this.parseTimeToSeconds("3:47,0") },
{ points: 20, result: this.parseTimeToSeconds("3:50,5") },
{ points: 19, result: this.parseTimeToSeconds("3:52,0") },
{ points: 18, result: this.parseTimeToSeconds("3:53,0") },
{ points: 17, result: this.parseTimeToSeconds("3:53,5") },
{ points: 16, result: this.parseTimeToSeconds("3:54,5") },
{ points: 15, result: this.parseTimeToSeconds("3:58,5") },
{ points: 14, result: this.parseTimeToSeconds("4:02,5") },
{ points: 13, result: this.parseTimeToSeconds("4:06,5") },
{ points: 12, result: this.parseTimeToSeconds("4:10,5") },
{ points: 11, result: this.parseTimeToSeconds("4:11,0") },
{ points: 10, result: this.parseTimeToSeconds("4:12,0") },
{ points: 9, result: this.parseTimeToSeconds("4:13,0") },
{ points: 8, result: this.parseTimeToSeconds("4:14,5") },
{ points: 7, result: this.parseTimeToSeconds("4:16,0") },
{ points: 6, result: this.parseTimeToSeconds("4:17,0") },
{ points: 5, result: this.parseTimeToSeconds("4:18,5") },
{ points: 4, result: this.parseTimeToSeconds("4:19,0") },
{ points: 3, result: this.parseTimeToSeconds("4:21,0") },
{ points: 2, result: this.parseTimeToSeconds("4:22,5") },
{ points: 1, result: this.parseTimeToSeconds("4:26,5") },
      ].sort((a, b) => a.result - b.result);

      // Бег 800/1000м — примерные данные (можно заменить на реальные)
      this.events.find(e => e.name === "Бег 800/1000м").resultsArray = [
          { points: 150, result: this.parseTimeToSeconds("2:50,0") },
{ points: 149, result: this.parseTimeToSeconds("2:54,5") },
{ points: 148, result: this.parseTimeToSeconds("2:56,5") },
{ points: 147, result: this.parseTimeToSeconds("2:58,5") },
{ points: 146, result: this.parseTimeToSeconds("3:00,5") },
{ points: 145, result: this.parseTimeToSeconds("3:02,5") },
{ points: 144, result: this.parseTimeToSeconds("3:05,0") },
{ points: 143, result: this.parseTimeToSeconds("3:07,5") },
{ points: 142, result: this.parseTimeToSeconds("3:10,0") },
{ points: 141, result: this.parseTimeToSeconds("3:12,5") },
{ points: 140, result: this.parseTimeToSeconds("3:15,0") },
{ points: 139, result: this.parseTimeToSeconds("3:17,5") },
{ points: 138, result: this.parseTimeToSeconds("3:20,0") },
{ points: 137, result: this.parseTimeToSeconds("3:22,5") },
{ points: 136, result: this.parseTimeToSeconds("3:25,0") },
{ points: 135, result: this.parseTimeToSeconds("3:27,5") },
{ points: 134, result: this.parseTimeToSeconds("3:30,0") },
{ points: 133, result: this.parseTimeToSeconds("3:32,5") },
{ points: 132, result: this.parseTimeToSeconds("3:35,0") },
{ points: 131, result: this.parseTimeToSeconds("3:37,5") },
{ points: 130, result: this.parseTimeToSeconds("3:40,0") },
{ points: 129, result: this.parseTimeToSeconds("3:42,5") },
{ points: 128, result: this.parseTimeToSeconds("3:45,0") },
{ points: 127, result: this.parseTimeToSeconds("3:47,5") },
{ points: 126, result: this.parseTimeToSeconds("3:50,0") },
{ points: 125, result: this.parseTimeToSeconds("3:52,5") },
{ points: 124, result: this.parseTimeToSeconds("3:55,0") },
{ points: 123, result: this.parseTimeToSeconds("3:57,5") },
{ points: 122, result: this.parseTimeToSeconds("4:00,0") },
{ points: 121, result: this.parseTimeToSeconds("4:03,7") },
{ points: 120, result: this.parseTimeToSeconds("4:07,4") },
{ points: 119, result: this.parseTimeToSeconds("4:11,1") },
{ points: 118, result: this.parseTimeToSeconds("4:14,8") },
{ points: 117, result: this.parseTimeToSeconds("4:18,5") },
{ points: 116, result: this.parseTimeToSeconds("4:22,2") },
{ points: 115, result: this.parseTimeToSeconds("4:25,9") },
{ points: 114, result: this.parseTimeToSeconds("4:29,6") },
{ points: 113, result: this.parseTimeToSeconds("4:33,3") },
{ points: 112, result: this.parseTimeToSeconds("4:37,0") },
{ points: 111, result: this.parseTimeToSeconds("4:40,7") },
{ points: 110, result: this.parseTimeToSeconds("4:44,4") },
{ points: 109, result: this.parseTimeToSeconds("4:48,1") },
{ points: 108, result: this.parseTimeToSeconds("4:51,8") },
{ points: 107, result: this.parseTimeToSeconds("4:55,5") },
{ points: 106, result: this.parseTimeToSeconds("4:59,2") },
{ points: 105, result: this.parseTimeToSeconds("5:02,9") },
{ points: 104, result: this.parseTimeToSeconds("5:06,6") },
{ points: 103, result: this.parseTimeToSeconds("5:10,3") },
{ points: 102, result: this.parseTimeToSeconds("5:14,0") },
{ points: 101, result: this.parseTimeToSeconds("5:17,7") },
{ points: 100, result: this.parseTimeToSeconds("5:21,4") },
{ points: 99, result: this.parseTimeToSeconds("5:25,1") },
{ points: 98, result: this.parseTimeToSeconds("5:28,8") },
{ points: 97, result: this.parseTimeToSeconds("5:32,5") },
{ points: 96, result: this.parseTimeToSeconds("5:36,2") },
{ points: 95, result: this.parseTimeToSeconds("5:39,9") },
{ points: 94, result: this.parseTimeToSeconds("5:43,6") },
{ points: 93, result: this.parseTimeToSeconds("5:47,3") },
{ points: 92, result: this.parseTimeToSeconds("5:50,0") },
{ points: 91, result: this.parseTimeToSeconds("5:50,6") },
{ points: 90, result: this.parseTimeToSeconds("5:51,2") },
{ points: 89, result: this.parseTimeToSeconds("5:51,8") },
{ points: 88, result: this.parseTimeToSeconds("5:52,4") },
{ points: 87, result: this.parseTimeToSeconds("5:53,0") },
{ points: 86, result: this.parseTimeToSeconds("5:53,6") },
{ points: 85, result: this.parseTimeToSeconds("5:54,2") },
{ points: 84, result: this.parseTimeToSeconds("5:54,8") },
{ points: 83, result: this.parseTimeToSeconds("5:55,4") },
{ points: 82, result: this.parseTimeToSeconds("5:56,0") },
{ points: 81, result: this.parseTimeToSeconds("5:56,6") },
{ points: 80, result: this.parseTimeToSeconds("5:57,2") },
{ points: 79, result: this.parseTimeToSeconds("5:57,8") },
{ points: 78, result: this.parseTimeToSeconds("5:58,4") },
{ points: 77, result: this.parseTimeToSeconds("5:59,0") },
{ points: 76, result: this.parseTimeToSeconds("5:59,6") },
{ points: 75, result: this.parseTimeToSeconds("6:00,2") },
{ points: 74, result: this.parseTimeToSeconds("6:00,8") },
{ points: 73, result: this.parseTimeToSeconds("6:01,4") },
{ points: 72, result: this.parseTimeToSeconds("6:02,0") },
{ points: 71, result: this.parseTimeToSeconds("6:02,6") },
{ points: 70, result: this.parseTimeToSeconds("6:03,2") },
{ points: 69, result: this.parseTimeToSeconds("6:03,8") },
{ points: 68, result: this.parseTimeToSeconds("6:04,4") },
{ points: 67, result: this.parseTimeToSeconds("6:05,0") },
{ points: 66, result: this.parseTimeToSeconds("6:05,6") },
{ points: 65, result: this.parseTimeToSeconds("6:06,2") },
{ points: 64, result: this.parseTimeToSeconds("6:06,8") },
{ points: 63, result: this.parseTimeToSeconds("6:07,4") },
{ points: 62, result: this.parseTimeToSeconds("6:08,0") },
{ points: 61, result: this.parseTimeToSeconds("6:08,6") },
{ points: 60, result: this.parseTimeToSeconds("6:09,2") },
{ points: 59, result: this.parseTimeToSeconds("6:09,8") },
{ points: 58, result: this.parseTimeToSeconds("6:10,4") },
{ points: 57, result: this.parseTimeToSeconds("6:11,0") },
{ points: 56, result: this.parseTimeToSeconds("6:11,6") },
{ points: 55, result: this.parseTimeToSeconds("6:12,2") },
{ points: 54, result: this.parseTimeToSeconds("6:12,8") },
{ points: 53, result: this.parseTimeToSeconds("6:13,4") },
{ points: 52, result: this.parseTimeToSeconds("6:14,0") },
{ points: 51, result: this.parseTimeToSeconds("6:14,6") },
{ points: 50, result: this.parseTimeToSeconds("6:15,2") },
{ points: 49, result: this.parseTimeToSeconds("6:15,8") },
{ points: 48, result: this.parseTimeToSeconds("6:16,4") },
{ points: 47, result: this.parseTimeToSeconds("6:17,0") },
{ points: 46, result: this.parseTimeToSeconds("6:17,6") },
{ points: 45, result: this.parseTimeToSeconds("6:18,2") },
{ points: 44, result: this.parseTimeToSeconds("6:18,8") },
{ points: 43, result: this.parseTimeToSeconds("6:19,4") },
{ points: 42, result: this.parseTimeToSeconds("6:20,0") },
{ points: 41, result: this.parseTimeToSeconds("6:20,6") },
{ points: 40, result: this.parseTimeToSeconds("6:21,2") },
{ points: 39, result: this.parseTimeToSeconds("6:21,8") },
{ points: 38, result: this.parseTimeToSeconds("6:22,4") },
{ points: 37, result: this.parseTimeToSeconds("6:23,0") },
{ points: 36, result: this.parseTimeToSeconds("6:23,6") },
{ points: 35, result: this.parseTimeToSeconds("6:24,2") },
{ points: 34, result: this.parseTimeToSeconds("6:24,8") },
{ points: 33, result: this.parseTimeToSeconds("6:25,4") },
{ points: 32, result: this.parseTimeToSeconds("6:26,0") },
{ points: 31, result: this.parseTimeToSeconds("6:26,6") },
{ points: 30, result: this.parseTimeToSeconds("6:27,2") },
{ points: 29, result: this.parseTimeToSeconds("6:27,8") },
{ points: 28, result: this.parseTimeToSeconds("6:28,4") },
{ points: 27, result: this.parseTimeToSeconds("6:29,0") },
{ points: 26, result: this.parseTimeToSeconds("6:29,6") },
{ points: 25, result: this.parseTimeToSeconds("6:30,2") },
{ points: 24, result: this.parseTimeToSeconds("6:30,8") },
{ points: 23, result: this.parseTimeToSeconds("6:31,4") },
{ points: 22, result: this.parseTimeToSeconds("6:32,0") },
{ points: 21, result: this.parseTimeToSeconds("6:32,6") },
{ points: 20, result: this.parseTimeToSeconds("6:33,2") },
{ points: 19, result: this.parseTimeToSeconds("6:33,8") },
{ points: 18, result: this.parseTimeToSeconds("6:34,4") },
{ points: 17, result: this.parseTimeToSeconds("6:35,0") },
{ points: 16, result: this.parseTimeToSeconds("6:35,6") },
{ points: 15, result: this.parseTimeToSeconds("6:36,2") },
{ points: 14, result: this.parseTimeToSeconds("6:36,8") },
{ points: 13, result: this.parseTimeToSeconds("6:37,4") },
{ points: 12, result: this.parseTimeToSeconds("6:38,0") },
{ points: 11, result: this.parseTimeToSeconds("6:38,6") },
{ points: 10, result: this.parseTimeToSeconds("6:39,2") },
{ points: 9, result: this.parseTimeToSeconds("6:39,8") },
{ points: 8, result: this.parseTimeToSeconds("6:40,4") },
{ points: 7, result: this.parseTimeToSeconds("6:41,0") },
{ points: 6, result: this.parseTimeToSeconds("6:41,6") },
{ points: 5, result: this.parseTimeToSeconds("6:42,2") },
{ points: 4, result: this.parseTimeToSeconds("6:42,8") },
{ points: 3, result: this.parseTimeToSeconds("6:43,4") },
{ points: 2, result: this.parseTimeToSeconds("6:44,0") },
{ points: 1, result: this.parseTimeToSeconds("6:44,6") },
      ].sort((a, b) => a.result - b.result);
    }
  },
  onTimeInput(index) {
    const event = this.events[index];
    const input = event.resultInput.trim();
    if (input === "") {
      event.result = 0;
      event.points = 0;
      return;
    }
    const seconds = this.parseTimeToSeconds(input);
    if (seconds === null) {
      event.points = 0;
      event.result = 0;
    } else {
      event.result = seconds;
      this.calculatePoints(index);
    }
  },
  calculatePoints(index) {
    const event = this.events[index];
    const result = event.result;
    const resultArray = event.resultsArray;
    const isTimeBased = event.isTimeBased;

    if (!result || resultArray.length === 0) {
      event.points = 0;
      return;
    }

    let low = 0;
    let high = resultArray.length - 1;
    let points = 0;

    if (isTimeBased) {
      // Для времени — ищем минимальный индекс с resultArray[mid].result >= result
      while (low <= high) {
        const mid = Math.floor((low + high) / 2);
        if (resultArray[mid].result >= result) {
          points = resultArray[mid].points;
          high = mid - 1;
        } else {
          low = mid + 1;
        }
      }
    } else {
      // Для прыжков и метаний — ищем максимальный индекс с resultArray[mid].result <= result
      while (low <= high) {
        const mid = Math.floor((low + high) / 2);
        if (resultArray[mid].result <= result) {
          points = resultArray[mid].points;
          low = mid + 1;
        } else {
          high = mid - 1;
        }
      }
    }

    event.points = points;
  },
},
computed: {
  totalPoints() {
    return this.events.reduce((sum, event) => sum + event.points, 0);
  },
},
};
</script>

<style>
@media only screen and (max-width: 768px) {
.competition {
  padding: 20px;
}

.event-form {
  margin: 20px 0;
  width: 100%;
}

label {
  width: 100%;
  display: block;
  margin-bottom: 5px;
  font-weight: 600;
}

input[type="number"],
input[type="text"] {
  width: 100%;
  padding: 10px;
  font-size: 16px;
  box-sizing: border-box;
  border: 1px solid #ccc;
  border-radius: 4px;
  outline: none;
  transition: border-color 0.3s ease;
}

input[type="number"]:focus,
input[type="text"]:focus {
  border-color: #66afe9;
  box-shadow: 0 0 5px rgba(102, 175, 233, 0.6);
}

span {
  font-size: 16px;
  margin-left: 10px;
}
}
</style>